name: Cypress e2e Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          build: npm run build
          start: npm start
          run: npm run e2e-test